### ISSUE TITLE
[bug] Server responds 500 when user tries to add the same question more than once

### ISSUE THREAD

**Issue by przytrzask** [typeofweb/devfaq#207]
### Steps to reproduce
1. Open add question form and fill it with required data
2. Repeat step 1 using exact the same values

<img width="1763" alt="Screenshot 2020-08-11 at 10 55 10" src="https://user-images.githubusercontent.com/20127089/89878353-b92b1180-dbc1-11ea-9570-a41ed57f41b0.png">

**Comment by mmiszy** [comment]
Fixed in https://github.com/typeofweb/devfaq/pull/443
