### ISSUE TITLE
Change content of element which triggers logout from service

### ISSUE THREAD

**Issue by grzegorzpokorski** [typeofweb/devfaq#476]
Obecnie wylogowanie z serwisu wywołuje kliknięcie na awatar zalogowanego użytkownika, który znajduje się w menu głównym, jak na załączonym poniżej przykładzie:

![Zrzut ekranu 2023-01-04 134107](https://user-images.githubusercontent.com/27455716/210557742-ce263da1-1e11-410a-bd82-2f92d7e03663.png)

Jest to trochę dezorientujące, gdyż nic jasno nie wskazuje jaki jest cel tego awatara. Sugeruję zmienić go na zwyczajny tekst 'wyloguj się'. Zachęcam do podawania swoich pomysłów 🙂

**Comment by AdiPol1359** [comment]
Zamiast dodawać nowy link do nawigacji, można zrobić menu, które otworzy się po kliknięciu w avatar: 
![Screenshot_2023-01-04-23-30-35-647_com android chrome](https://user-images.githubusercontent.com/27779154/210662516-aa6e49a1-1bb7-4f9b-8e49-b32d7f77b00a.png)
Tylko nie wiem czy takie rozwiązanie będzie dobrze wyglądało i działało z aktualną nawigacją na urządzeniach mobilnych, która jest rozciągnięta na cały ekran.

**Comment by grzegorzpokorski** [comment]
zamykam po scaleniu PR: https://github.com/typeofweb/devfaq/pull/495
