### ISSUE TITLE
Niedziałające kolory borderów

### ISSUE THREAD

**Issue by AdiPol1359** [typeofweb/devfaq#487]
Uruchamiając stronę w trybie produkcyjnym, kolory ``oklch`` są niepoprawnie zamienianie w kolorach borderów. W konsekwencji na przeglądarkach innych niż safari wyświetlają się niewłaściwe kolory:
![IMG_20230104_234541](https://user-images.githubusercontent.com/27779154/210664787-2aa223f4-7375-438c-8b8b-ea476b701ed5.png)
![IMG_20230104_234627](https://user-images.githubusercontent.com/27779154/210664812-a978701f-b00e-4382-a336-e2b54ca70b36.png)

**Comment by grzegorzpokorski** [comment]
Ciekawe jest to, że błąd występuje w przypadku klas tailwinda służących do ustawiania koloru obramowań, a w przypadku koloru tekstu już nie. 

![image](https://user-images.githubusercontent.com/27455716/211127970-0237a1f8-10bd-4a8d-94d5-c9e8fd3cf04b.png)

**Comment by AdiPol1359** [comment]
> Ciekawe jest to, że błąd występuje w przypadku klas tailwinda służących do ustawiania koloru obramowań, a w przypadku koloru tekstu już nie.
> 
> ![image](https://user-images.githubusercontent.com/27455716/211127970-0237a1f8-10bd-4a8d-94d5-c9e8fd3cf04b.png)

otworzyłem issue na githubie, bo wydaje mi się, że to jest błąd w pluginie: https://github.com/csstools/postcss-plugins/issues/766

**Comment by grzegorzpokorski** [comment]
@AdiPol1359 przeczytałem sobie wątek issue które stworzyłeś i jeśli rzeczywiście problem leży w cssnano to ciekawe wydają się te watki:
- https://github.com/cssnano/cssnano/issues/1163
- https://github.com/cssnano/cssnano/issues/935

**Comment by AdiPol1359** [comment]
> @AdiPol1359 przeczytałem sobie wątek issue które stworzyłeś i jeśli rzeczywiście problem leży w cssnano to ciekawe wydają się te watki:
> 
> * [[Bug] : `mergeLonghand` plugin removes fallbacks for older browsers cssnano/cssnano#1163](https://github.com/cssnano/cssnano/issues/1163)
> * [How to disable optimization for overrides? cssnano/cssnano#935](https://github.com/cssnano/cssnano/issues/935)

Z tego co zauważyłem to zmiana presetu na ``lite`` nie usuwają się niepotrzebnie fallback styles, więc może to jest jakiś sposób na rozwiązanie tego problemu, ale mi się nie udało tego naprawić. Tutaj możesz to przetestować: https://cssnano.co/playground/#eyJpbnB1dCI6Ii5mb28xIHtcbiAgY29sb3I6IHJlZDtcbiAgY29sb3I6IGJsdWU7XG59XG4uZm9vMiB7XG4gIGJvcmRlcjogMXB4IHNvbGlkIHJlZDtcbiAgYm9yZGVyOiAxcHggc29saWQgYmx1ZTtcbn0iLCJjb25maWciOiJjc3NuYW5vLXByZXNldC1kZWZhdWx0In0=

**Comment by grzegorzpokorski** [comment]
https://github.com/vercel/next.js/discussions/44687

**Comment by grzegorzpokorski** [comment]
Otwarłem issue do cssnano: https://github.com/cssnano/cssnano/issues/1461 oraz issue do cssnano-simple: https://github.com/Timer/cssnano-simple/issues/29

Najlepiej byłoby, aby cssnano poprawiło działanie opcji `mergeLonghand`, bo wątpię, aby w wtyczce `cssnano-simple` wykorzystywanej przez next.js na stałe wyłączyli tą opcje. Można pomyśleć również czy nie dało by się tych klas wykorzystujących OKLCH wstawić w [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports).
