### ISSUE TITLE
Propozycja zmiany wyglądu opcji do zarządzania pytaniami w panelu administratora

### ISSUE THREAD

**Issue by grzegorzpokorski** [typeofweb/devfaq#499]
Wraz z rozwojem aplikacji dochodzi coraz więcej opcji do zarządzania pytaniami w panelu administratora. O ile na desktopie wygląda to dobrze to na smartfonie już niekoniecznie: 

![app devfaq localhost_3000_questions_js_1(iPhone 12 Pro) (3)](https://user-images.githubusercontent.com/27455716/212204567-2dac3f36-f6df-463f-bc1e-5128d197de58.png)

Poniżej propozycja zmian:

![app devfaq localhost_3000_questions_js_1(iPhone 12 Pro) (1)](https://user-images.githubusercontent.com/27455716/212204617-61cba316-8b62-4b43-95bb-0fd81d417931.png)
![app devfaq localhost_3000_questions_js_1(iPhone 12 Pro) (2)](https://user-images.githubusercontent.com/27455716/212204623-98a6b709-f2b4-4090-b68e-cee98ecfa1fe.png)

Analogiczne 'menu' można by zastosować wszędzie, gdzie przy pytaniu znajdą się jakieś opcje do jego zarządzania.

Chętnie przeczytam co o tym sądzicie. Może ktoś podsunie inny pomysł?

**Comment by mmiszy** [comment]
Trzy opcje spokojnie się zmieszczą na mobile, nie trzeba robić rozwijanego menu. Trzeba natomiast poprawić style bo ewidentnie się rozjechało.

**Comment by grzegorzpokorski** [comment]
> Trzy opcje spokojnie się zmieszczą na mobile, nie trzeba robić rozwijanego menu. Trzeba natomiast poprawić style bo ewidentnie się rozjechało.

Ok, poprawie style, aby przyciski były w jednej kolumnie.
