### ISSUE TITLE
Add contributing.md 

### ISSUE THREAD

**Issue by drillprop** [typeofweb/devfaq#78]
As the title says, it would be nice to list steps how to contribute to this project. 

There are some templates on github like, for example, [this one](https://gist.github.com/PurpleBooth/b24679402957c63ec426). I'm not sure what will fit to this project and how detailed should be. Maybe someone has bigger experience in contributing to open source. I think it requires discussion. I'll try to send some inspirations/templates too.

**Comment by drillprop** [comment]
Something like [this one](https://github.com/testing-library/react-testing-library/blob/master/CONTRIBUTING.md) looks very nice. Simple and straightforward.

**Comment by mmiszy** [comment]
I'm on it!
