### ISSUE TITLE
Change SCSS variables to CSS custom properties

### ISSUE THREAD

**Issue by mmiszy** [typeofweb/devfaq#79]

**Comment by mczeplowski** [comment]
I can take it

**Comment by mmiszy** [comment]
What about https://github.com/typeofweb/devfaq-www/issues/8 @mczeplowski ? :)

**Comment by mmiszy** [comment]
Do you want me to continue with that?

**Comment by mczeplowski** [comment]
Oh sorry, I didnt notice that you updated that task. I will try to do it both today.

**Comment by mmiszy** [comment]
I also replied to you on Discord with some comments :)

-- 
Michał Miszczyszyn
Consulting JavaScript
Type of Web
typeofweb.com
michal@miszczyszyn.com
<https://facebook.com/typeofweb>
<https://www.linkedin.com/in/mmiszczyszyn/>

**Comment by mczeplowski** [comment]
On Discord?

**Comment by mmiszy** [comment]
https://discordapp.com/channels/440163731704643589/440222239107842089/718159279617605683

Maybe that wasn't you? XD
